apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: hello-world
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-world
  filterTags:
    pattern: '^(?P<ts>\d{14})-[a-f0-9]{8}$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
